baseURL = "https://www.example.com"
languageCode = "en-us"
title = "Andy C.H. Chang"
theme = "hugo-digital-garden-theme"
themesdir = "./themes"
copyright = "Andy C.H. Chang ©"


[params]
  name = "Andy Chia-Hao Chang"
  description = "Software - Coffee - Traveling - Art"
  initials = "AC"
  googleAnalytics = ""

  [[params.social]]
    name = "Instagram"
    link = "https://www.instagram.com/andyrochi"
    icon = "fab fa-instagram"

  [[params.social]]
    name = "Github"
    link = "https://github.com/andyrochi"
    icon = "fab fa-github"

  [[params.social]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/andychchang/"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Digital Garden"
    url = "/garden/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3


[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'